OS = input("What OS do you have? (Unix or Windows) ")

if OS == "U" or OS == "Unix" or OS == "unix":
    delimiter=":"

elif OS == "W" or OS == "Windows" or OS == "windows":
    print("Classpath will be good, but the shell scripts will be useless.")
    delimiter=";"

else:
    print("Aborting.")
    exit()

SQLiteLocation = input("Input location of sqlite-jdbc.jar, full path. ")
ToolsLocation = input("Input location of tools.jar, full path. ")
JUnitLocation = input("Input location of junit4.jar, full path. ")
SrcLocation = "src/"
TestsLocation = "tests/:."

cpString = """# Classpath generated by createMakefile.py.
CLASSPATH = {0}{1}{2}{1}{3}{1}{4}{1}{5}

all:
\tjavac -cp $(CLASSPATH) src/com/psu/group9/*.java
\tjavac -cp $(CLASSPATH) tests/*.java

clean:
\trm src/com/psu/group9/*.class
\trm tests/*.java"""

runTerminalString = """# Classpath generated by createMakefile.py.
CLASSPATH="{0}{1}{2}{1}{3}{1}{4}{1}{5}"

java -cp ${{CLASSPATH}} com.psu.group9.Terminal"""

runTestsString = """# Classpath generated by createMakefile.py.
CLASSPATH="{0}{1}{2}{1}{3}{1}{4}{1}{5}"

java -cp ${{CLASSPATH}} org.junit.runner.JUnitCore \
DBTest \
PatientTest \
ProviderTest \
TestService \
TestTransaction"""


f = open("Makefile", "w")
f.write(cpString.format(SQLiteLocation, delimiter, ToolsLocation, JUnitLocation,
                        SrcLocation, TestsLocation))
f.close()


f = open("runTerminal.sh", "w")
f.write(runTerminalString.format(SQLiteLocation, delimiter, ToolsLocation, 
                                 JUnitLocation, SrcLocation, TestsLocation))
f.close()

f = open("runTests.sh", "w")
f.write(runTestsString.format(SQLiteLocation, delimiter, ToolsLocation, 
                                 JUnitLocation, SrcLocation, TestsLocation))
f.close()
